-- Crimson Rep -- Supabase schema
--
-- Run this once in the Supabase SQL Editor (Project -> SQL Editor -> New
-- query -> paste this whole file -> Run). It creates one table per data
-- domain the app used to keep in localStorage, all scoped to auth.uid()
-- via row-level security so a user can only ever read/write their own rows.
--
-- Auth itself needs no table here -- Supabase's built-in auth.users handles
-- signup/login, and every table below just references auth.users(id).
--
-- Safe to run more than once: every CREATE TABLE uses IF NOT EXISTS, and
-- every policy is dropped first (IF EXISTS) before being recreated, since
-- Postgres has no CREATE POLICY IF NOT EXISTS -- re-running this without
-- the DROP would fail on "policy already exists" for every table.

create extension if not exists pgcrypto;

-- ---------- profiles (Split Builder questionnaire answers + profile card) ----------
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  age integer,
  bodyweight numeric,
  bodyweight_unit text,
  sex text,
  days_per_week integer,
  training_weekdays jsonb,
  time_per_session integer,
  experience_level text,
  name text,
  profile_picture_type text,
  profile_picture_url text,
  preset_avatar_id text,
  updated_at timestamptz not null default now()
);

-- ADD COLUMN IF NOT EXISTS so this is safe to re-run against a profiles
-- table that already existed before the profile card feature did.
alter table public.profiles add column if not exists name text;
alter table public.profiles add column if not exists profile_picture_type text;
alter table public.profiles add column if not exists profile_picture_url text;
alter table public.profiles add column if not exists preset_avatar_id text;

-- Explicit "has this user ever completed the mandatory first-time profile
-- setup" flag, set true only by ProfileSetup's onSave (see ProfileSetup.js
-- / router.js). Deliberately a dedicated column rather than inferring
-- completion from `name` being non-null -- less ambiguous, and easier to
-- diagnose if a write ever silently fails to persist.
alter table public.profiles add column if not exists setup_complete boolean not null default false;

-- Unique shareable ID in the form "user<6-digit-number>" (e.g.
-- "user163745") -- a random number, not sequential, so ids can't be
-- enumerated/guessed, generated by generate_unique_public_id() below,
-- which loops until it finds one not already in use. security definer so
-- that uniqueness check sees every row in the table regardless of who's
-- triggering it -- an ordinary authenticated user's own SELECT on
-- `profiles` only sees their own/connections' rows per RLS, which would
-- make the "not exists" check unreliable without this.
create or replace function public.generate_unique_public_id()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  candidate text;
begin
  loop
    candidate := 'user' || (100000 + floor(random() * 900000))::bigint::text;
    exit when not exists (select 1 from public.profiles where public_id = candidate);
  end loop;
  return candidate;
end;
$$;

grant execute on function public.generate_unique_public_id() to authenticated;

alter table public.profiles add column if not exists public_id text;

-- Assigns a fresh id to any row that has none yet, or still has one in the
-- old 8-char hex format from an earlier version of this migration.
update public.profiles
set public_id = public.generate_unique_public_id()
where public_id is null or public_id !~ '^user[0-9]+$';

alter table public.profiles alter column public_id set default public.generate_unique_public_id();
create unique index if not exists profiles_public_id_idx on public.profiles (public_id);

alter table public.profiles enable row level security;
drop policy if exists "profiles_owner" on public.profiles;
create policy "profiles_owner" on public.profiles
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------- entries (logged sets / 1RM history) ----------
create table if not exists public.entries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  lift text not null,
  weight numeric not null,
  reps integer not null,
  unit text not null,
  estimated_1rm numeric not null,
  epley numeric,
  brzycki numeric,
  lombardi numeric,
  bodyweight numeric,
  sex text,
  added_weight numeric,
  date timestamptz not null default now()
);

alter table public.entries enable row level security;
drop policy if exists "entries_owner" on public.entries;
create policy "entries_owner" on public.entries
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create index if not exists entries_user_id_idx on public.entries (user_id);

-- Logging a set now computes a TARGET to attempt, not an automatic PB --
-- attempt_status tracks whether the user confirmed they actually hit it.
-- null = logged, not yet confirmed either way (a fresh pending attempt);
-- 'succeeded' = confirmed hit, counts toward the confirmed PB used
-- everywhere (standards gauge, exercise goals, the community 'pr'
-- activity, strength challenge progress); 'failed' = confirmed miss,
-- stays in History but never counts as a PB.
--
-- The backfill only ever runs the FIRST time this migration is applied,
-- guarded by the column-existence check below: every entry logged
-- before this feature shipped is grandfathered in as 'succeeded' so
-- nobody's existing PB history is retroactively stripped. On every
-- later re-run of this whole file the column already exists, so this
-- entire block is skipped -- it never re-touches a future pending
-- (null) entry just because the file gets run again.
do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'entries' and column_name = 'attempt_status'
  ) then
    alter table public.entries add column attempt_status text check (attempt_status in ('succeeded', 'failed'));
    update public.entries set attempt_status = 'succeeded';
  end if;
end $$;

-- ---------- settings (display unit + last-used form defaults + tour flags) ----------
create table if not exists public.settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_unit text,
  form_defaults jsonb,
  tour_seen boolean not null default false,
  achievement_tour_seen boolean not null default false
);

-- ADD COLUMN IF NOT EXISTS so this is safe to re-run against a settings
-- table that already existed before the achievement mini-tour did.
alter table public.settings add column if not exists achievement_tour_seen boolean not null default false;

alter table public.settings enable row level security;
drop policy if exists "settings_owner" on public.settings;
create policy "settings_owner" on public.settings
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------- splits (Build My Split's generated weekly plan) ----------
create table if not exists public.splits (
  user_id uuid primary key references auth.users(id) on delete cascade,
  days jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.splits enable row level security;
drop policy if exists "splits_owner" on public.splits;
create policy "splits_owner" on public.splits
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------- completions (per-calendar-date workout completion log) ----------
create table if not exists public.completions (
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  day_of_week integer,
  completed boolean not null default false,
  photo_url text,
  auto_detected boolean not null default false,
  completed_at timestamptz,
  primary key (user_id, date)
);

-- ADD COLUMN IF NOT EXISTS so this is safe to re-run against a completions
-- table that already existed before workout-completion verification did.
alter table public.completions add column if not exists photo_url text;
alter table public.completions add column if not exists auto_detected boolean not null default false;
alter table public.completions add column if not exists completed_at timestamptz;

alter table public.completions enable row level security;
drop policy if exists "completions_owner" on public.completions;
create policy "completions_owner" on public.completions
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------- gym_locations (saved gyms for workout-completion auto-detection
-- via geolocation -- see App.Components.GymAutoComplete) ----------
create table if not exists public.gym_locations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  lat double precision not null,
  lng double precision not null,
  created_at timestamptz not null default now()
);

alter table public.gym_locations enable row level security;
drop policy if exists "gym_locations_owner" on public.gym_locations;
create policy "gym_locations_owner" on public.gym_locations
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create index if not exists gym_locations_user_id_idx on public.gym_locations (user_id);

-- ---------- streaks ----------
create table if not exists public.streaks (
  user_id uuid primary key references auth.users(id) on delete cascade,
  count integer not null default 0,
  credited_dates jsonb not null default '{}'::jsonb,
  last_checked_date_key text
);

alter table public.streaks enable row level security;
drop policy if exists "streaks_owner" on public.streaks;
create policy "streaks_owner" on public.streaks
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------- bodyweight_log ----------
create table if not exists public.bodyweight_log (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  date timestamptz not null default now(),
  weight numeric not null,
  unit text not null
);

alter table public.bodyweight_log enable row level security;
drop policy if exists "bodyweight_log_owner" on public.bodyweight_log;
create policy "bodyweight_log_owner" on public.bodyweight_log
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create index if not exists bodyweight_log_user_id_idx on public.bodyweight_log (user_id);

-- ---------- goals (single active goal per user; absent row = no goal set) ----------
create table if not exists public.goals (
  user_id uuid primary key references auth.users(id) on delete cascade,
  type text not null,
  direction text,
  amount numeric,
  start_weight numeric,
  target_weight numeric not null,
  unit text not null,
  lift text,
  created_at timestamptz not null default now(),
  achieved boolean not null default false,
  achieved_at timestamptz
);

alter table public.goals enable row level security;
drop policy if exists "goals_owner" on public.goals;
create policy "goals_owner" on public.goals
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------- achievements (archived reached goals -- never deleted when a new goal starts) ----------
create table if not exists public.achievements (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null,
  lift text,
  direction text,
  start_value numeric,
  target_value numeric not null,
  amount numeric,
  unit text not null,
  achieved_at timestamptz not null,
  tier text not null
);

alter table public.achievements enable row level security;
drop policy if exists "achievements_owner" on public.achievements;
create policy "achievements_owner" on public.achievements
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create index if not exists achievements_user_id_idx on public.achievements (user_id);

-- ---------- themes (Settings page appearance customization) ----------
create table if not exists public.themes (
  user_id uuid primary key references auth.users(id) on delete cascade,
  bg text,
  surface text,
  accent text,
  text_color text,
  density text,
  view_style text,
  font_size text
);

alter table public.themes enable row level security;
drop policy if exists "themes_owner" on public.themes;
create policy "themes_owner" on public.themes
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Replaces the old free-form accent-color picker with a plain light/dark
-- mode toggle (see App.Theme) -- bg/surface/accent/text_color above are no
-- longer written or read by the app. Left in place rather than dropped:
-- existing rows keep whatever values they already have, but nothing
-- reads them anymore -- App.Theme resolves the actual colors for
-- whichever mode is picked entirely in code.
alter table public.themes add column if not exists mode text not null default 'dark' check (mode in ('dark', 'light'));

-- ---------- user_added_exercises (tracks which curated-pool exercises this
-- user has added to their own picker -- the pool's own data (names,
-- muscles, standards, descriptions) lives in code, not here) ----------
create table if not exists public.user_added_exercises (
  user_id uuid not null references auth.users(id) on delete cascade,
  exercise_key text not null,
  added_at timestamptz not null default now(),
  primary key (user_id, exercise_key)
);

alter table public.user_added_exercises enable row level security;
drop policy if exists "user_added_exercises_owner" on public.user_added_exercises;
create policy "user_added_exercises_owner" on public.user_added_exercises
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------- user_custom_exercises (genuinely custom exercises a user typed
-- in that weren't found in the curated pool -- no standards data, ever) ----------
create table if not exists public.user_custom_exercises (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  primary_muscle text not null,
  secondary_muscle text,
  description text,
  pattern text,
  created_at timestamptz not null default now()
);

alter table public.user_custom_exercises enable row level security;
drop policy if exists "user_custom_exercises_owner" on public.user_custom_exercises;
create policy "user_custom_exercises_owner" on public.user_custom_exercises
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create index if not exists user_custom_exercises_user_id_idx on public.user_custom_exercises (user_id);

-- ==================== Community & Challenges ====================

-- ---------- friend_requests (doubles as the friendships table -- an
-- accepted row *is* the friendship. Declining or unfriending is just a
-- delete, so there's never a "declined" status to clean up, and no
-- separate friendships table copying rows over on accept.) ----------
create table if not exists public.friend_requests (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted')),
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  constraint friend_requests_no_self check (sender_id <> recipient_id)
);

-- One row per unordered pair regardless of who sent it -- least/greatest
-- normalizes (a,b) and (b,a) to the same key so a duplicate request in
-- either direction is rejected outright.
create unique index if not exists friend_requests_pair_idx
  on public.friend_requests (least(sender_id, recipient_id), greatest(sender_id, recipient_id));
create index if not exists friend_requests_recipient_idx on public.friend_requests (recipient_id);
create index if not exists friend_requests_sender_idx on public.friend_requests (sender_id);

alter table public.friend_requests enable row level security;

drop policy if exists "friend_requests_select" on public.friend_requests;
create policy "friend_requests_select" on public.friend_requests
  for select using (auth.uid() = sender_id or auth.uid() = recipient_id);

drop policy if exists "friend_requests_insert" on public.friend_requests;
create policy "friend_requests_insert" on public.friend_requests
  for insert with check (auth.uid() = sender_id);

-- Only the recipient can accept -- there's no "decline" update, that's a
-- delete instead (see the delete policy below).
drop policy if exists "friend_requests_update" on public.friend_requests;
create policy "friend_requests_update" on public.friend_requests
  for update using (auth.uid() = recipient_id) with check (auth.uid() = recipient_id);

-- Either side can remove the row: the sender cancelling a pending request,
-- the recipient declining one, or either party unfriending an accepted one.
drop policy if exists "friend_requests_delete" on public.friend_requests;
create policy "friend_requests_delete" on public.friend_requests
  for delete using (auth.uid() = sender_id or auth.uid() = recipient_id);

-- Tracks whether this request has already been surfaced to the recipient
-- as a toast -- set true the moment it's shown, whether that happens live
-- (Realtime, while they're online) or as a one-time catch-up the next
-- time they open the app after being offline when it arrived. The
-- existing friend_requests_update policy (recipient-only) already covers
-- the recipient setting this on their own incoming rows -- no RLS change
-- needed for this column.
alter table public.friend_requests add column if not exists notified boolean not null default false;

-- Realtime: the recipient's client needs to hear about a new row the
-- instant it's inserted (see App.Social.subscribeToFriendRequests). This
-- table isn't part of the realtime publication by default, and
-- `alter publication ... add table` has no IF NOT EXISTS form, hence the
-- guard -- see the note in the accompanying message about confirming
-- this in the Dashboard (Database -> Replication) if this block errors,
-- e.g. because the supabase_realtime publication doesn't exist under
-- that exact name on this project.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'friend_requests'
  ) then
    alter publication supabase_realtime add table public.friend_requests;
  end if;
end $$;

-- Shared "are these two users friends" check -- accepted rows only (unlike
-- profiles_select_connections below, which also counts pending requests
-- for a different reason). security definer for the same reason as
-- is_community_member: a caller's own SELECT on friend_requests is
-- already scoped to rows they're a party to, which is exactly what's
-- being tested here, so bypassing RLS internally avoids any risk of the
-- same class of recursion and keeps this reusable from policies on other
-- tables (streaks, achievements) without each duplicating the query.
create or replace function public.are_friends(p_user_a uuid, p_user_b uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.friend_requests
    where status = 'accepted'
      and ((sender_id = p_user_a and recipient_id = p_user_b) or (sender_id = p_user_b and recipient_id = p_user_a))
  );
$$;

grant execute on function public.are_friends(uuid, uuid) to authenticated;

-- ---------- communities ----------
create table if not exists public.communities (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  visibility text not null check (visibility in ('public', 'private')),
  invite_code text not null default encode(gen_random_bytes(6), 'hex'),
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create unique index if not exists communities_invite_code_idx on public.communities (invite_code);

alter table public.communities enable row level security;

-- Basic community metadata (name/visibility/invite_code/creator) isn't
-- sensitive by itself, so any signed-in user can read any row by id.
-- Privacy for a private community comes from two other places instead: (1)
-- the app's own directory/browse query only ever filters on
-- visibility = 'public', so a private community is never listed for
-- discovery, and (2) its invite_code is unguessable (48 bits of entropy),
-- so the only way to ever reach one is already having the link -- the same
-- trust model as any "anyone with the link" share. The actually sensitive
-- data -- who's a member, what challenges exist, everyone's progress -- is
-- separately locked down below to real members only.
drop policy if exists "communities_select" on public.communities;
create policy "communities_select" on public.communities
  for select using (true);

drop policy if exists "communities_insert" on public.communities;
create policy "communities_insert" on public.communities
  for insert with check (created_by = auth.uid());

-- ---------- community_members ----------
create table if not exists public.community_members (
  community_id uuid not null references public.communities(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (community_id, user_id)
);

alter table public.community_members enable row level security;

-- A member can see every membership row for any community they themselves
-- belong to (so the full member list renders for them), not just their
-- own row. The naive way to write this is a subquery on community_members
-- from within community_members' own policy -- that looks like the
-- standard "group membership" RLS pattern seen in a lot of writeups, but
-- it actually makes Postgres throw "infinite recursion detected in policy
-- for relation community_members" (42P17), because evaluating the policy
-- requires re-evaluating the same policy on the same table. Worse, that
-- error doesn't stay contained: profiles_select_connections (further
-- down) also queries community_members to check shared-community
-- membership, so ANY query touching profiles' SELECT visibility --
-- including an upsert's ON CONFLICT check -- transitively re-triggers this
-- same recursion and fails with an error that looks like it's about a
-- completely unrelated table. is_community_member() sidesteps this: it's
-- security definer, so its internal query bypasses RLS entirely instead
-- of re-invoking community_members_select.
create or replace function public.is_community_member(p_community_id uuid, p_user_id uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.community_members
    where community_id = p_community_id and user_id = p_user_id
  );
$$;

grant execute on function public.is_community_member(uuid, uuid) to authenticated;

drop policy if exists "community_members_select" on public.community_members;
create policy "community_members_select" on public.community_members
  for select using (
    user_id = auth.uid()
    or public.is_community_member(community_id, auth.uid())
  );

-- Joining a PUBLIC community directly needs no invite code -- straight
-- insert. Joining a PRIVATE one is NOT permitted through this policy (no
-- code check is expressible in a column-only RLS predicate); that path
-- goes through join_community_by_code() below instead, which runs as
-- security definer specifically so a private community can be joined
-- without ever being SELECT-able by non-members first. The creator is
-- always allowed to add themselves regardless of visibility, so creating a
-- private community still auto-joins its own creator via a plain insert.
--
-- "Invite a friend to a community you created" (App.Communities.
-- inviteFriendToCommunity) does NOT insert here directly -- it goes
-- through community_invites below instead, requiring the friend to
-- accept. accept_community_invite() is security definer, so it performs
-- that eventual membership insert bypassing RLS entirely; this policy
-- deliberately does NOT grant the invited user (or the creator on their
-- behalf) any direct insert path, so the only way into a community you
-- didn't create/self-join-as-public is accepting an invite or a code.
drop policy if exists "community_members_insert" on public.community_members;
create policy "community_members_insert" on public.community_members
  for insert with check (
    user_id = auth.uid()
    and exists (
      select 1 from public.communities c
      where c.id = community_id and (c.visibility = 'public' or c.created_by = auth.uid())
    )
  );

drop policy if exists "community_members_delete" on public.community_members;
create policy "community_members_delete" on public.community_members
  for delete using (user_id = auth.uid());

-- ---------- community_invites (invite a friend to a community you
-- created -- requires their acceptance, same philosophy as
-- friend_requests: no separate "declined" status, declining/cancelling is
-- just a delete) ----------
create table if not exists public.community_invites (
  id uuid primary key default gen_random_uuid(),
  community_id uuid not null references public.communities(id) on delete cascade,
  invited_by uuid not null references auth.users(id) on delete cascade,
  invited_user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted')),
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  notified boolean not null default false,
  unique (community_id, invited_user_id)
);

create index if not exists community_invites_invited_user_idx on public.community_invites (invited_user_id);

alter table public.community_invites enable row level security;

drop policy if exists "community_invites_select" on public.community_invites;
create policy "community_invites_select" on public.community_invites
  for select using (auth.uid() = invited_by or auth.uid() = invited_user_id);

-- Only a community's creator can send one, and only to an actual friend --
-- mirrors the guard that used to live on community_members_insert before
-- this became a proper request/accept flow.
drop policy if exists "community_invites_insert" on public.community_invites;
create policy "community_invites_insert" on public.community_invites
  for insert with check (
    invited_by = auth.uid()
    and exists (select 1 from public.communities c where c.id = community_id and c.created_by = auth.uid())
    and public.are_friends(auth.uid(), invited_user_id)
  );

-- Only the invited user can accept (there's no "decline" update -- that's
-- a delete, see below), same pattern as friend_requests_update.
drop policy if exists "community_invites_update" on public.community_invites;
create policy "community_invites_update" on public.community_invites
  for update using (auth.uid() = invited_user_id) with check (auth.uid() = invited_user_id);

-- The invited user can decline (delete their own pending invite), or the
-- original inviter can cancel one they sent.
drop policy if exists "community_invites_delete" on public.community_invites;
create policy "community_invites_delete" on public.community_invites
  for delete using (auth.uid() = invited_by or auth.uid() = invited_user_id);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'community_invites'
  ) then
    alter publication supabase_realtime add table public.community_invites;
  end if;
end $$;

-- Accepting an invite has to do two things atomically: mark the invite
-- accepted, and actually add the membership row -- community_members_insert
-- deliberately grants no direct path for this (see above), so this
-- security-definer function does both, bypassing RLS internally, after
-- verifying the caller IS the invited user and the invite is still pending.
-- Returns the community_id (rather than void) so the client can log a
-- member_joined community_activity row without a second round trip.
-- Postgres can't change an existing function's return type via CREATE OR
-- REPLACE -- the old (void-returning) version has to be dropped first, so
-- this is safe to re-run whether or not the old version still exists.
drop function if exists public.accept_community_invite(uuid);
create or replace function public.accept_community_invite(p_invite_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_community_id uuid;
begin
  update public.community_invites
  set status = 'accepted', responded_at = now()
  where id = p_invite_id and invited_user_id = auth.uid() and status = 'pending'
  returning community_id into v_community_id;

  if v_community_id is null then
    raise exception 'Invite not found or already handled';
  end if;

  insert into public.community_members (community_id, user_id)
  values (v_community_id, auth.uid())
  on conflict (community_id, user_id) do nothing;

  return v_community_id;
end;
$$;

grant execute on function public.accept_community_invite(uuid) to authenticated;

-- ---------- join_community_by_code: the only way to join a PRIVATE
-- community. security definer bypasses RLS internally so the lookup by
-- code works even though a non-member can't otherwise SELECT a private
-- community row at all -- the invite code itself is the credential, same
-- as the public-metadata tradeoff explained above. ----------
create or replace function public.join_community_by_code(p_invite_code text)
returns table (id uuid, name text, visibility text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
  v_name text;
  v_visibility text;
begin
  select c.id, c.name, c.visibility into v_id, v_name, v_visibility
  from public.communities c
  where c.invite_code = p_invite_code;

  if v_id is null then
    raise exception 'Invalid invite code';
  end if;

  insert into public.community_members (community_id, user_id)
  values (v_id, auth.uid())
  on conflict (community_id, user_id) do nothing;

  return query select v_id, v_name, v_visibility;
end;
$$;

grant execute on function public.join_community_by_code(text) to authenticated;

-- ---------- find_user_by_public_id: resolves the 8-char shareable ID from
-- the "add a friend" flow to a user, before any friendship exists yet (so
-- the normal friends-or-community-members profiles policy below doesn't
-- apply). security definer bypasses RLS, but deliberately returns only
-- identity fields -- never age/bodyweight -- so looking someone up by ID
-- confirms who they are without exposing anything more. ----------
create or replace function public.find_user_by_public_id(p_public_id text)
returns table (
  user_id uuid, name text, profile_picture_type text,
  profile_picture_url text, preset_avatar_id text
)
language sql
security definer
set search_path = public
as $$
  select p.user_id, p.name, p.profile_picture_type, p.profile_picture_url, p.preset_avatar_id
  from public.profiles p
  where p.public_id = lower(p_public_id);
$$;

grant execute on function public.find_user_by_public_id(text) to authenticated;

-- ---------- challenges ----------
-- lift_label is a denormalized copy of the exercise's display name,
-- captured once from the CREATOR's own client at creation time. Needed
-- because `lift` can point at one member's private custom exercise (see
-- user_custom_exercises) which a different member's client has no way to
-- resolve to a name -- storing the label once avoids that cross-user
-- lookup entirely.
create table if not exists public.challenges (
  id uuid primary key default gen_random_uuid(),
  community_id uuid not null references public.communities(id) on delete cascade,
  created_by uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('gain', 'loss', 'strength')),
  lift text,
  lift_label text,
  target_kg numeric,
  target_percent numeric,
  mode text not null check (mode in ('race', 'leaderboard')),
  start_date date not null,
  end_date date not null,
  ended_at timestamptz,
  winner_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint challenges_dates check (end_date >= start_date)
);

create index if not exists challenges_community_id_idx on public.challenges (community_id);

alter table public.challenges enable row level security;

drop policy if exists "challenges_select" on public.challenges;
create policy "challenges_select" on public.challenges
  for select using (
    exists (select 1 from public.community_members m where m.community_id = challenges.community_id and m.user_id = auth.uid())
  );

drop policy if exists "challenges_insert" on public.challenges;
create policy "challenges_insert" on public.challenges
  for insert with check (
    created_by = auth.uid()
    and exists (select 1 from public.community_members m where m.community_id = challenges.community_id and m.user_id = auth.uid())
  );

-- Lets any community member write the shared finalize fields
-- (winner_id/ended_at) the moment their own client notices a Race target
-- was hit or a Leaderboard window closed -- the same opportunistic
-- self-heal pattern already used for goal achievements elsewhere in this
-- app (App.Goals.ensureArchived). The app never exposes a generic
-- "edit challenge" UI, so in practice only those two fields ever get
-- written this way.
drop policy if exists "challenges_update" on public.challenges;
create policy "challenges_update" on public.challenges
  for update using (
    exists (select 1 from public.community_members m where m.community_id = challenges.community_id and m.user_id = auth.uid())
  ) with check (
    exists (select 1 from public.community_members m where m.community_id = challenges.community_id and m.user_id = auth.uid())
  );

-- ---------- challenge_participants ----------
create table if not exists public.challenge_participants (
  challenge_id uuid not null references public.challenges(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'invited' check (status in ('invited', 'accepted', 'declined')),
  start_value numeric,
  current_value numeric,
  updated_at timestamptz,
  joined_at timestamptz not null default now(),
  responded_at timestamptz,
  primary key (challenge_id, user_id)
);

create index if not exists challenge_participants_challenge_id_idx on public.challenge_participants (challenge_id);

alter table public.challenge_participants enable row level security;

-- Any fellow community member can see everyone's participation/progress in
-- a shared challenge -- that's the whole point of a leaderboard. Nobody
-- outside the community sees this table at all. Note this only ever
-- exposes a single derived current_value number per person, never anyone's
-- raw entries/bodyweight_log rows (those keep their existing owner-only
-- RLS completely untouched) -- each participant computes and writes their
-- own current_value from their own locally-cached history.
drop policy if exists "challenge_participants_select" on public.challenge_participants;
create policy "challenge_participants_select" on public.challenge_participants
  for select using (
    exists (
      select 1 from public.challenges c
      join public.community_members m on m.community_id = c.community_id
      where c.id = challenge_participants.challenge_id and m.user_id = auth.uid()
    )
  );

-- The challenge creator inserts an "invited" row for every other member
-- (plus their own, pre-accepted) at creation time; a user can also always
-- insert their own row directly.
drop policy if exists "challenge_participants_insert" on public.challenge_participants;
create policy "challenge_participants_insert" on public.challenge_participants
  for insert with check (
    user_id = auth.uid()
    or exists (select 1 from public.challenges c where c.id = challenge_participants.challenge_id and c.created_by = auth.uid())
  );

-- A participant accepts/declines their own invite and updates their own
-- progress -- never anyone else's.
drop policy if exists "challenge_participants_update" on public.challenge_participants;
create policy "challenge_participants_update" on public.challenge_participants
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ---------- profiles: extra read access for friends & community members
-- ----------
-- Placed here (rather than up in the profiles section) because it
-- references friend_requests and community_members, which don't exist
-- yet at that point in the script. This is a SECOND, additive SELECT
-- policy alongside profiles_owner's "for all" -- Postgres ORs same-command
-- policies together, so this only ever widens SELECT (letting you read a
-- friend's or fellow community member's full profile row -- name, avatar,
-- age, bodyweight) and never touches INSERT/UPDATE/DELETE, which stay
-- owner-only via profiles_owner. Covers PENDING friend_requests rows too
-- (not just accepted ones) -- both sides already identified each other via
-- a public_id lookup to create the row at all, so the incoming/outgoing
-- request UI needs to show a name, not a bare user id. Anyone with no
-- request/friendship/community in common is only ever looked up through
-- find_user_by_public_id() above, which exposes name/avatar alone, not
-- age/bodyweight.
drop policy if exists "profiles_select_connections" on public.profiles;
create policy "profiles_select_connections" on public.profiles
  for select using (
    exists (
      select 1 from public.friend_requests fr
      where ((fr.sender_id = auth.uid() and fr.recipient_id = profiles.user_id)
          or (fr.recipient_id = auth.uid() and fr.sender_id = profiles.user_id))
    )
    or exists (
      select 1 from public.community_members m1
      join public.community_members m2 on m2.community_id = m1.community_id
      where m1.user_id = auth.uid() and m2.user_id = profiles.user_id
    )
  );

-- ---------- streaks & achievements: read access for friends ----------
-- Friend profile viewing (App.Social.getFriendProfile) needs a friend's
-- streak count and medal list, neither of which any earlier policy
-- exposes -- both tables were, and remain, fully owner-only for
-- insert/update/delete via their existing "for all" policies; these are
-- second, additive SELECT-only policies that widen read access to
-- confirmed (accepted) friends specifically, narrower than
-- profiles_select_connections above (which also covers community members
-- and pending requests, for different reasons that don't apply here).
drop policy if exists "streaks_select_friends" on public.streaks;
create policy "streaks_select_friends" on public.streaks
  for select using (public.are_friends(auth.uid(), user_id));

drop policy if exists "achievements_select_friends" on public.achievements;
create policy "achievements_select_friends" on public.achievements
  for select using (public.are_friends(auth.uid(), user_id));

-- ---------- profile-photos storage bucket (uploaded profile pictures) ----------
-- Private bucket -- there is no public URL for these files. The app always
-- fetches a short-lived signed URL (App.Storage.getProfilePhotoUrl) to
-- display a photo, and only ever does that for the signed-in user's own
-- profile, so nobody else's photo is ever requested through the app. Each
-- user's photo is stored at a fixed path "<user_id>/photo" (no extension --
-- the real image type travels in the object's contentType instead), so a
-- re-upload always replaces the previous file rather than leaving orphans.
insert into storage.buckets (id, name, public)
values ('profile-photos', 'profile-photos', false)
on conflict (id) do nothing;

-- storage.foldername(name) splits the object path on "/" -- for a path like
-- "<user_id>/photo" this returns an array whose first element is the
-- <user_id> segment, which is what every policy below checks against
-- auth.uid(). If your bucket insert above fails with a permissions error,
-- create the bucket instead via Dashboard -> Storage -> New bucket, name
-- "profile-photos", Public OFF -- then just run the four policies below.
drop policy if exists "profile_photos_select_own" on storage.objects;
create policy "profile_photos_select_own" on storage.objects
  for select using (
    bucket_id = 'profile-photos' and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "profile_photos_insert_own" on storage.objects;
create policy "profile_photos_insert_own" on storage.objects
  for insert with check (
    bucket_id = 'profile-photos' and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "profile_photos_update_own" on storage.objects;
create policy "profile_photos_update_own" on storage.objects
  for update using (
    bucket_id = 'profile-photos' and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "profile_photos_delete_own" on storage.objects;
create policy "profile_photos_delete_own" on storage.objects
  for delete using (
    bucket_id = 'profile-photos' and auth.uid()::text = (storage.foldername(name))[1]
  );

-- ---------- workout-photos storage bucket (manual workout-completion
-- proof photos) ---------- Same shape as profile-photos in every respect
-- -- private bucket, per-user-folder RLS, owner-only (no
-- friends/community read access here, unlike profile photos -- this is
-- private proof-of-attendance data, nobody else ever needs to see it).
-- Path is "<user_id>/<date>.jpg" (one per completed day) rather than a
-- fixed path, since unlike a profile photo there can be many of these per
-- user over time.
insert into storage.buckets (id, name, public)
values ('workout-photos', 'workout-photos', false)
on conflict (id) do nothing;

drop policy if exists "workout_photos_select_own" on storage.objects;
create policy "workout_photos_select_own" on storage.objects
  for select using (
    bucket_id = 'workout-photos' and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "workout_photos_insert_own" on storage.objects;
create policy "workout_photos_insert_own" on storage.objects
  for insert with check (
    bucket_id = 'workout-photos' and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "workout_photos_update_own" on storage.objects;
create policy "workout_photos_update_own" on storage.objects
  for update using (
    bucket_id = 'workout-photos' and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "workout_photos_delete_own" on storage.objects;
create policy "workout_photos_delete_own" on storage.objects
  for delete using (
    bucket_id = 'workout-photos' and auth.uid()::text = (storage.foldername(name))[1]
  );

-- Community & Challenges needs friends/community members to be able to
-- view each other's uploaded profile photos (the profile card and the
-- challenge leaderboard both show them), which the owner-only select
-- policy above doesn't allow. Same additive-policy approach as
-- profiles_select_connections: this ORs in an extra allowed case for
-- select without touching insert/update/delete, which remain owner-only.
-- Placed here (not up with the other profile-photos policies) because it
-- references friend_requests/community_members, created further down.
drop policy if exists "profile_photos_select_connections" on storage.objects;
create policy "profile_photos_select_connections" on storage.objects
  for select using (
    bucket_id = 'profile-photos'
    and (
      exists (
        select 1 from public.friend_requests fr
        where fr.status = 'accepted'
          and ((fr.sender_id = auth.uid() and fr.recipient_id::text = (storage.foldername(name))[1])
            or (fr.recipient_id = auth.uid() and fr.sender_id::text = (storage.foldername(name))[1]))
      )
      or exists (
        select 1 from public.community_members m1
        join public.community_members m2 on m2.community_id = m1.community_id
        where m1.user_id = auth.uid() and m2.user_id::text = (storage.foldername(name))[1]
      )
    )
  );

-- ---------- community_activity (per-community feed: new PRs, completed
-- challenges, streak milestones, members joining) ----------
-- lift_label is denormalized the same way and for the same reason as
-- challenges.lift_label: `lift` can point at the ACTING user's own
-- private custom exercise, which a different community member's client
-- has no way to resolve to a name -- the logging user's own client
-- captures the label once at insert time instead.
create table if not exists public.community_activity (
  id uuid primary key default gen_random_uuid(),
  community_id uuid not null references public.communities(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('pr', 'challenge_completed', 'streak_milestone', 'member_joined')),
  lift text,
  lift_label text,
  value numeric,
  unit text,
  challenge_id uuid references public.challenges(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists community_activity_feed_idx on public.community_activity (community_id, created_at desc);

-- Dedup for the three event types that should only ever post once per
-- (community, user, thing) -- a repeat attempt (e.g. re-viewing a
-- leaderboard challenge after its window closed, or the streak
-- recalculation re-running on every navigation while still at the same
-- milestone) just hits a unique-violation, which the app treats as
-- "already logged, fine" rather than an error. 'pr' has no dedup: each
-- new best is a genuinely distinct event even if the same lift gets
-- multiple PRs over time.
create unique index if not exists community_activity_streak_dedup
  on public.community_activity (community_id, user_id, value)
  where type = 'streak_milestone';

create unique index if not exists community_activity_challenge_dedup
  on public.community_activity (community_id, user_id, challenge_id)
  where type = 'challenge_completed';

create unique index if not exists community_activity_joined_dedup
  on public.community_activity (community_id, user_id)
  where type = 'member_joined';

alter table public.community_activity enable row level security;

drop policy if exists "community_activity_select" on public.community_activity;
create policy "community_activity_select" on public.community_activity
  for select using (public.is_community_member(community_id, auth.uid()));

drop policy if exists "community_activity_insert" on public.community_activity;
create policy "community_activity_insert" on public.community_activity
  for insert with check (
    user_id = auth.uid() and public.is_community_member(community_id, auth.uid())
  );

-- ---------- push_subscriptions (Web Push opt-in: one combined toggle,
-- not per-trigger-type -- workout-reminder and streak-at-risk pushes both
-- read this same row) ----------
-- One row per user (a re-subscribe just upserts fresh endpoint/keys over
-- the same row) rather than one row per device/browser -- matches the
-- single-toggle, single-subscription scope this feature was asked for.
-- auth_key (not "auth", which would shadow the auth.* schema name) holds
-- the subscription's auth secret; p256dh its public key -- both required
-- by the Web Push protocol alongside the endpoint URL.
create table if not exists public.push_subscriptions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth_key text not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;
drop policy if exists "push_subscriptions_owner" on public.push_subscriptions;
create policy "push_subscriptions_owner" on public.push_subscriptions
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- No policy grants the daily cron job access -- it isn't a signed-in user
-- at all, so RLS (owner-only above) would block it from ever seeing
-- anyone else's row. It authenticates with the Supabase SERVICE ROLE key
-- instead (see api/send-notifications.js), which bypasses RLS entirely
-- by design -- the standard, correct way for a trusted backend job to
-- read across every user, same as any admin/cron integration.

-- ---------- verification ----------
-- Run this separately after the script above to confirm, from Postgres's
-- own catalog (not the SQL Editor's pre-run warning banner, which can fire
-- on partial/re-runs or stale query text rather than the actual state of
-- your database). Every row here should show rowsecurity = true.
--
-- select schemaname, tablename, rowsecurity
-- from pg_tables
-- where schemaname = 'public'
-- order by tablename;
