-- Crimson Rep -- Supabase schema
--
-- Run this once in the Supabase SQL Editor (Project -> SQL Editor -> New
-- query -> paste this whole file -> Run). It creates one table per data
-- domain the app used to keep in localStorage, all scoped to auth.uid()
-- via row-level security so a user can only ever read/write their own rows.
--
-- Auth itself needs no table here -- Supabase's built-in auth.users handles
-- signup/login, and every table below just references auth.users(id).
--
-- Safe to run more than once: every CREATE TABLE uses IF NOT EXISTS, and
-- every policy is dropped first (IF EXISTS) before being recreated, since
-- Postgres has no CREATE POLICY IF NOT EXISTS -- re-running this without
-- the DROP would fail on "policy already exists" for every table.

create extension if not exists pgcrypto;

-- ---------- profiles (Split Builder questionnaire answers + profile card) ----------
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  age integer,
  bodyweight numeric,
  bodyweight_unit text,
  sex text,
  days_per_week integer,
  training_weekdays jsonb,
  time_per_session integer,
  experience_level text,
  name text,
  profile_picture_type text,
  profile_picture_url text,
  preset_avatar_id text,
  updated_at timestamptz not null default now()
);

-- ADD COLUMN IF NOT EXISTS so this is safe to re-run against a profiles
-- table that already existed before the profile card feature did.
alter table public.profiles add column if not exists name text;
alter table public.profiles add column if not exists profile_picture_type text;
alter table public.profiles add column if not exists profile_picture_url text;
alter table public.profiles add column if not exists preset_avatar_id text;

-- Explicit "has this user ever completed the mandatory first-time profile
-- setup" flag, set true only by ProfileSetup's onSave (see ProfileSetup.js
-- / router.js). Deliberately a dedicated column rather than inferring
-- completion from `name` being non-null -- less ambiguous, and easier to
-- diagnose if a write ever silently fails to persist.
alter table public.profiles add column if not exists setup_complete boolean not null default false;

-- Unique shareable ID in the form "user<6-digit-number>" (e.g.
-- "user163745") -- a random number, not sequential, so ids can't be
-- enumerated/guessed, generated by generate_unique_public_id() below,
-- which loops until it finds one not already in use. security definer so
-- that uniqueness check sees every row in the table regardless of who's
-- triggering it -- an ordinary authenticated user's own SELECT on
-- `profiles` only sees their own/connections' rows per RLS, which would
-- make the "not exists" check unreliable without this.
create or replace function public.generate_unique_public_id()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  candidate text;
begin
  loop
    candidate := 'user' || (100000 + floor(random() * 900000))::bigint::text;
    exit when not exists (select 1 from public.profiles where public_id = candidate);
  end loop;
  return candidate;
end;
$$;

grant execute on function public.generate_unique_public_id() to authenticated;

alter table public.profiles add column if not exists public_id text;

-- Assigns a fresh id to any row that has none yet, or still has one in the
-- old 8-char hex format from an earlier version of this migration.
update public.profiles
set public_id = public.generate_unique_public_id()
where public_id is null or public_id !~ '^user[0-9]+$';

alter table public.profiles alter column public_id set default public.generate_unique_public_id();
create unique index if not exists profiles_public_id_idx on public.profiles (public_id);

alter table public.profiles enable row level security;
drop policy if exists "profiles_owner" on public.profiles;
create policy "profiles_owner" on public.profiles
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------- entries (logged sets / 1RM history) ----------
create table if not exists public.entries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  lift text not null,
  weight numeric not null,
  reps integer not null,
  unit text not null,
  estimated_1rm numeric not null,
  epley numeric,
  brzycki numeric,
  lombardi numeric,
  bodyweight numeric,
  sex text,
  added_weight numeric,
  date timestamptz not null default now()
);

alter table public.entries enable row level security;
drop policy if exists "entries_owner" on public.entries;
create policy "entries_owner" on public.entries
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create index if not exists entries_user_id_idx on public.entries (user_id);

-- ---------- settings (display unit + last-used form defaults + tour flags) ----------
create table if not exists public.settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_unit text,
  form_defaults jsonb,
  tour_seen boolean not null default false,
  achievement_tour_seen boolean not null default false
);

-- ADD COLUMN IF NOT EXISTS so this is safe to re-run against a settings
-- table that already existed before the achievement mini-tour did.
alter table public.settings add column if not exists achievement_tour_seen boolean not null default false;

alter table public.settings enable row level security;
drop policy if exists "settings_owner" on public.settings;
create policy "settings_owner" on public.settings
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------- splits (Build My Split's generated weekly plan) ----------
create table if not exists public.splits (
  user_id uuid primary key references auth.users(id) on delete cascade,
  days jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.splits enable row level security;
drop policy if exists "splits_owner" on public.splits;
create policy "splits_owner" on public.splits
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------- completions (per-calendar-date workout completion log) ----------
create table if not exists public.completions (
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  day_of_week integer,
  completed boolean not null default false,
  primary key (user_id, date)
);

alter table public.completions enable row level security;
drop policy if exists "completions_owner" on public.completions;
create policy "completions_owner" on public.completions
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------- streaks ----------
create table if not exists public.streaks (
  user_id uuid primary key references auth.users(id) on delete cascade,
  count integer not null default 0,
  credited_dates jsonb not null default '{}'::jsonb,
  last_checked_date_key text
);

alter table public.streaks enable row level security;
drop policy if exists "streaks_owner" on public.streaks;
create policy "streaks_owner" on public.streaks
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------- bodyweight_log ----------
create table if not exists public.bodyweight_log (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  date timestamptz not null default now(),
  weight numeric not null,
  unit text not null
);

alter table public.bodyweight_log enable row level security;
drop policy if exists "bodyweight_log_owner" on public.bodyweight_log;
create policy "bodyweight_log_owner" on public.bodyweight_log
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create index if not exists bodyweight_log_user_id_idx on public.bodyweight_log (user_id);

-- ---------- goals (single active goal per user; absent row = no goal set) ----------
create table if not exists public.goals (
  user_id uuid primary key references auth.users(id) on delete cascade,
  type text not null,
  direction text,
  amount numeric,
  start_weight numeric,
  target_weight numeric not null,
  unit text not null,
  lift text,
  created_at timestamptz not null default now(),
  achieved boolean not null default false,
  achieved_at timestamptz
);

alter table public.goals enable row level security;
drop policy if exists "goals_owner" on public.goals;
create policy "goals_owner" on public.goals
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------- achievements (archived reached goals -- never deleted when a new goal starts) ----------
create table if not exists public.achievements (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null,
  lift text,
  direction text,
  start_value numeric,
  target_value numeric not null,
  amount numeric,
  unit text not null,
  achieved_at timestamptz not null,
  tier text not null
);

alter table public.achievements enable row level security;
drop policy if exists "achievements_owner" on public.achievements;
create policy "achievements_owner" on public.achievements
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create index if not exists achievements_user_id_idx on public.achievements (user_id);

-- ---------- themes (Settings page appearance customization) ----------
create table if not exists public.themes (
  user_id uuid primary key references auth.users(id) on delete cascade,
  bg text,
  surface text,
  accent text,
  text_color text,
  density text,
  view_style text,
  font_size text
);

alter table public.themes enable row level security;
drop policy if exists "themes_owner" on public.themes;
create policy "themes_owner" on public.themes
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------- user_added_exercises (tracks which curated-pool exercises this
-- user has added to their own picker -- the pool's own data (names,
-- muscles, standards, descriptions) lives in code, not here) ----------
create table if not exists public.user_added_exercises (
  user_id uuid not null references auth.users(id) on delete cascade,
  exercise_key text not null,
  added_at timestamptz not null default now(),
  primary key (user_id, exercise_key)
);

alter table public.user_added_exercises enable row level security;
drop policy if exists "user_added_exercises_owner" on public.user_added_exercises;
create policy "user_added_exercises_owner" on public.user_added_exercises
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------- user_custom_exercises (genuinely custom exercises a user typed
-- in that weren't found in the curated pool -- no standards data, ever) ----------
create table if not exists public.user_custom_exercises (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  primary_muscle text not null,
  secondary_muscle text,
  description text,
  pattern text,
  created_at timestamptz not null default now()
);

alter table public.user_custom_exercises enable row level security;
drop policy if exists "user_custom_exercises_owner" on public.user_custom_exercises;
create policy "user_custom_exercises_owner" on public.user_custom_exercises
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create index if not exists user_custom_exercises_user_id_idx on public.user_custom_exercises (user_id);

-- ==================== Community & Challenges ====================

-- ---------- friend_requests (doubles as the friendships table -- an
-- accepted row *is* the friendship. Declining or unfriending is just a
-- delete, so there's never a "declined" status to clean up, and no
-- separate friendships table copying rows over on accept.) ----------
create table if not exists public.friend_requests (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted')),
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  constraint friend_requests_no_self check (sender_id <> recipient_id)
);

-- One row per unordered pair regardless of who sent it -- least/greatest
-- normalizes (a,b) and (b,a) to the same key so a duplicate request in
-- either direction is rejected outright.
create unique index if not exists friend_requests_pair_idx
  on public.friend_requests (least(sender_id, recipient_id), greatest(sender_id, recipient_id));
create index if not exists friend_requests_recipient_idx on public.friend_requests (recipient_id);
create index if not exists friend_requests_sender_idx on public.friend_requests (sender_id);

alter table public.friend_requests enable row level security;

drop policy if exists "friend_requests_select" on public.friend_requests;
create policy "friend_requests_select" on public.friend_requests
  for select using (auth.uid() = sender_id or auth.uid() = recipient_id);

drop policy if exists "friend_requests_insert" on public.friend_requests;
create policy "friend_requests_insert" on public.friend_requests
  for insert with check (auth.uid() = sender_id);

-- Only the recipient can accept -- there's no "decline" update, that's a
-- delete instead (see the delete policy below).
drop policy if exists "friend_requests_update" on public.friend_requests;
create policy "friend_requests_update" on public.friend_requests
  for update using (auth.uid() = recipient_id) with check (auth.uid() = recipient_id);

-- Either side can remove the row: the sender cancelling a pending request,
-- the recipient declining one, or either party unfriending an accepted one.
drop policy if exists "friend_requests_delete" on public.friend_requests;
create policy "friend_requests_delete" on public.friend_requests
  for delete using (auth.uid() = sender_id or auth.uid() = recipient_id);

-- ---------- communities ----------
create table if not exists public.communities (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  visibility text not null check (visibility in ('public', 'private')),
  invite_code text not null default encode(gen_random_bytes(6), 'hex'),
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create unique index if not exists communities_invite_code_idx on public.communities (invite_code);

alter table public.communities enable row level security;

-- Basic community metadata (name/visibility/invite_code/creator) isn't
-- sensitive by itself, so any signed-in user can read any row by id.
-- Privacy for a private community comes from two other places instead: (1)
-- the app's own directory/browse query only ever filters on
-- visibility = 'public', so a private community is never listed for
-- discovery, and (2) its invite_code is unguessable (48 bits of entropy),
-- so the only way to ever reach one is already having the link -- the same
-- trust model as any "anyone with the link" share. The actually sensitive
-- data -- who's a member, what challenges exist, everyone's progress -- is
-- separately locked down below to real members only.
drop policy if exists "communities_select" on public.communities;
create policy "communities_select" on public.communities
  for select using (true);

drop policy if exists "communities_insert" on public.communities;
create policy "communities_insert" on public.communities
  for insert with check (created_by = auth.uid());

-- ---------- community_members ----------
create table if not exists public.community_members (
  community_id uuid not null references public.communities(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (community_id, user_id)
);

alter table public.community_members enable row level security;

-- Standard "group membership" RLS pattern: a member can see every
-- membership row for any community they themselves belong to (so the full
-- member list renders for them), not just their own row.
drop policy if exists "community_members_select" on public.community_members;
create policy "community_members_select" on public.community_members
  for select using (
    user_id = auth.uid()
    or community_id in (select community_id from public.community_members where user_id = auth.uid())
  );

-- Joining a PUBLIC community directly needs no invite code -- straight
-- insert. Joining a PRIVATE one is NOT permitted through this policy (no
-- code check is expressible in a column-only RLS predicate); that path
-- goes through join_community_by_code() below instead, which runs as
-- security definer specifically so a private community can be joined
-- without ever being SELECT-able by non-members first. The creator is
-- always allowed to add themselves regardless of visibility, so creating a
-- private community still auto-joins its own creator via a plain insert.
drop policy if exists "community_members_insert" on public.community_members;
create policy "community_members_insert" on public.community_members
  for insert with check (
    user_id = auth.uid()
    and exists (
      select 1 from public.communities c
      where c.id = community_id and (c.visibility = 'public' or c.created_by = auth.uid())
    )
  );

drop policy if exists "community_members_delete" on public.community_members;
create policy "community_members_delete" on public.community_members
  for delete using (user_id = auth.uid());

-- ---------- join_community_by_code: the only way to join a PRIVATE
-- community. security definer bypasses RLS internally so the lookup by
-- code works even though a non-member can't otherwise SELECT a private
-- community row at all -- the invite code itself is the credential, same
-- as the public-metadata tradeoff explained above. ----------
create or replace function public.join_community_by_code(p_invite_code text)
returns table (id uuid, name text, visibility text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
  v_name text;
  v_visibility text;
begin
  select c.id, c.name, c.visibility into v_id, v_name, v_visibility
  from public.communities c
  where c.invite_code = p_invite_code;

  if v_id is null then
    raise exception 'Invalid invite code';
  end if;

  insert into public.community_members (community_id, user_id)
  values (v_id, auth.uid())
  on conflict (community_id, user_id) do nothing;

  return query select v_id, v_name, v_visibility;
end;
$$;

grant execute on function public.join_community_by_code(text) to authenticated;

-- ---------- find_user_by_public_id: resolves the 8-char shareable ID from
-- the "add a friend" flow to a user, before any friendship exists yet (so
-- the normal friends-or-community-members profiles policy below doesn't
-- apply). security definer bypasses RLS, but deliberately returns only
-- identity fields -- never age/bodyweight -- so looking someone up by ID
-- confirms who they are without exposing anything more. ----------
create or replace function public.find_user_by_public_id(p_public_id text)
returns table (
  user_id uuid, name text, profile_picture_type text,
  profile_picture_url text, preset_avatar_id text
)
language sql
security definer
set search_path = public
as $$
  select p.user_id, p.name, p.profile_picture_type, p.profile_picture_url, p.preset_avatar_id
  from public.profiles p
  where p.public_id = lower(p_public_id);
$$;

grant execute on function public.find_user_by_public_id(text) to authenticated;

-- ---------- challenges ----------
-- lift_label is a denormalized copy of the exercise's display name,
-- captured once from the CREATOR's own client at creation time. Needed
-- because `lift` can point at one member's private custom exercise (see
-- user_custom_exercises) which a different member's client has no way to
-- resolve to a name -- storing the label once avoids that cross-user
-- lookup entirely.
create table if not exists public.challenges (
  id uuid primary key default gen_random_uuid(),
  community_id uuid not null references public.communities(id) on delete cascade,
  created_by uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('gain', 'loss', 'strength')),
  lift text,
  lift_label text,
  target_kg numeric,
  target_percent numeric,
  mode text not null check (mode in ('race', 'leaderboard')),
  start_date date not null,
  end_date date not null,
  ended_at timestamptz,
  winner_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint challenges_dates check (end_date >= start_date)
);

create index if not exists challenges_community_id_idx on public.challenges (community_id);

alter table public.challenges enable row level security;

drop policy if exists "challenges_select" on public.challenges;
create policy "challenges_select" on public.challenges
  for select using (
    exists (select 1 from public.community_members m where m.community_id = challenges.community_id and m.user_id = auth.uid())
  );

drop policy if exists "challenges_insert" on public.challenges;
create policy "challenges_insert" on public.challenges
  for insert with check (
    created_by = auth.uid()
    and exists (select 1 from public.community_members m where m.community_id = challenges.community_id and m.user_id = auth.uid())
  );

-- Lets any community member write the shared finalize fields
-- (winner_id/ended_at) the moment their own client notices a Race target
-- was hit or a Leaderboard window closed -- the same opportunistic
-- self-heal pattern already used for goal achievements elsewhere in this
-- app (App.Goals.ensureArchived). The app never exposes a generic
-- "edit challenge" UI, so in practice only those two fields ever get
-- written this way.
drop policy if exists "challenges_update" on public.challenges;
create policy "challenges_update" on public.challenges
  for update using (
    exists (select 1 from public.community_members m where m.community_id = challenges.community_id and m.user_id = auth.uid())
  ) with check (
    exists (select 1 from public.community_members m where m.community_id = challenges.community_id and m.user_id = auth.uid())
  );

-- ---------- challenge_participants ----------
create table if not exists public.challenge_participants (
  challenge_id uuid not null references public.challenges(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'invited' check (status in ('invited', 'accepted', 'declined')),
  start_value numeric,
  current_value numeric,
  updated_at timestamptz,
  joined_at timestamptz not null default now(),
  responded_at timestamptz,
  primary key (challenge_id, user_id)
);

create index if not exists challenge_participants_challenge_id_idx on public.challenge_participants (challenge_id);

alter table public.challenge_participants enable row level security;

-- Any fellow community member can see everyone's participation/progress in
-- a shared challenge -- that's the whole point of a leaderboard. Nobody
-- outside the community sees this table at all. Note this only ever
-- exposes a single derived current_value number per person, never anyone's
-- raw entries/bodyweight_log rows (those keep their existing owner-only
-- RLS completely untouched) -- each participant computes and writes their
-- own current_value from their own locally-cached history.
drop policy if exists "challenge_participants_select" on public.challenge_participants;
create policy "challenge_participants_select" on public.challenge_participants
  for select using (
    exists (
      select 1 from public.challenges c
      join public.community_members m on m.community_id = c.community_id
      where c.id = challenge_participants.challenge_id and m.user_id = auth.uid()
    )
  );

-- The challenge creator inserts an "invited" row for every other member
-- (plus their own, pre-accepted) at creation time; a user can also always
-- insert their own row directly.
drop policy if exists "challenge_participants_insert" on public.challenge_participants;
create policy "challenge_participants_insert" on public.challenge_participants
  for insert with check (
    user_id = auth.uid()
    or exists (select 1 from public.challenges c where c.id = challenge_participants.challenge_id and c.created_by = auth.uid())
  );

-- A participant accepts/declines their own invite and updates their own
-- progress -- never anyone else's.
drop policy if exists "challenge_participants_update" on public.challenge_participants;
create policy "challenge_participants_update" on public.challenge_participants
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ---------- profiles: extra read access for friends & community members
-- ----------
-- Placed here (rather than up in the profiles section) because it
-- references friend_requests and community_members, which don't exist
-- yet at that point in the script. This is a SECOND, additive SELECT
-- policy alongside profiles_owner's "for all" -- Postgres ORs same-command
-- policies together, so this only ever widens SELECT (letting you read a
-- friend's or fellow community member's full profile row -- name, avatar,
-- age, bodyweight) and never touches INSERT/UPDATE/DELETE, which stay
-- owner-only via profiles_owner. Covers PENDING friend_requests rows too
-- (not just accepted ones) -- both sides already identified each other via
-- a public_id lookup to create the row at all, so the incoming/outgoing
-- request UI needs to show a name, not a bare user id. Anyone with no
-- request/friendship/community in common is only ever looked up through
-- find_user_by_public_id() above, which exposes name/avatar alone, not
-- age/bodyweight.
drop policy if exists "profiles_select_connections" on public.profiles;
create policy "profiles_select_connections" on public.profiles
  for select using (
    exists (
      select 1 from public.friend_requests fr
      where ((fr.sender_id = auth.uid() and fr.recipient_id = profiles.user_id)
          or (fr.recipient_id = auth.uid() and fr.sender_id = profiles.user_id))
    )
    or exists (
      select 1 from public.community_members m1
      join public.community_members m2 on m2.community_id = m1.community_id
      where m1.user_id = auth.uid() and m2.user_id = profiles.user_id
    )
  );

-- ---------- profile-photos storage bucket (uploaded profile pictures) ----------
-- Private bucket -- there is no public URL for these files. The app always
-- fetches a short-lived signed URL (App.Storage.getProfilePhotoUrl) to
-- display a photo, and only ever does that for the signed-in user's own
-- profile, so nobody else's photo is ever requested through the app. Each
-- user's photo is stored at a fixed path "<user_id>/photo" (no extension --
-- the real image type travels in the object's contentType instead), so a
-- re-upload always replaces the previous file rather than leaving orphans.
insert into storage.buckets (id, name, public)
values ('profile-photos', 'profile-photos', false)
on conflict (id) do nothing;

-- storage.foldername(name) splits the object path on "/" -- for a path like
-- "<user_id>/photo" this returns an array whose first element is the
-- <user_id> segment, which is what every policy below checks against
-- auth.uid(). If your bucket insert above fails with a permissions error,
-- create the bucket instead via Dashboard -> Storage -> New bucket, name
-- "profile-photos", Public OFF -- then just run the four policies below.
drop policy if exists "profile_photos_select_own" on storage.objects;
create policy "profile_photos_select_own" on storage.objects
  for select using (
    bucket_id = 'profile-photos' and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "profile_photos_insert_own" on storage.objects;
create policy "profile_photos_insert_own" on storage.objects
  for insert with check (
    bucket_id = 'profile-photos' and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "profile_photos_update_own" on storage.objects;
create policy "profile_photos_update_own" on storage.objects
  for update using (
    bucket_id = 'profile-photos' and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "profile_photos_delete_own" on storage.objects;
create policy "profile_photos_delete_own" on storage.objects
  for delete using (
    bucket_id = 'profile-photos' and auth.uid()::text = (storage.foldername(name))[1]
  );

-- Community & Challenges needs friends/community members to be able to
-- view each other's uploaded profile photos (the profile card and the
-- challenge leaderboard both show them), which the owner-only select
-- policy above doesn't allow. Same additive-policy approach as
-- profiles_select_connections: this ORs in an extra allowed case for
-- select without touching insert/update/delete, which remain owner-only.
-- Placed here (not up with the other profile-photos policies) because it
-- references friend_requests/community_members, created further down.
drop policy if exists "profile_photos_select_connections" on storage.objects;
create policy "profile_photos_select_connections" on storage.objects
  for select using (
    bucket_id = 'profile-photos'
    and (
      exists (
        select 1 from public.friend_requests fr
        where fr.status = 'accepted'
          and ((fr.sender_id = auth.uid() and fr.recipient_id::text = (storage.foldername(name))[1])
            or (fr.recipient_id = auth.uid() and fr.sender_id::text = (storage.foldername(name))[1]))
      )
      or exists (
        select 1 from public.community_members m1
        join public.community_members m2 on m2.community_id = m1.community_id
        where m1.user_id = auth.uid() and m2.user_id::text = (storage.foldername(name))[1]
      )
    )
  );

-- ---------- verification ----------
-- Run this separately after the script above to confirm, from Postgres's
-- own catalog (not the SQL Editor's pre-run warning banner, which can fire
-- on partial/re-runs or stale query text rather than the actual state of
-- your database). Every row here should show rowsecurity = true.
--
-- select schemaname, tablename, rowsecurity
-- from pg_tables
-- where schemaname = 'public'
-- order by tablename;
